"""Add product API

Revision ID: 0d80fe0562eb
Revises: 1a31ce608336
Create Date: 2025-02-04 18:36:06.317033

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0d80fe0562eb'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('reference_type', sa.Enum('REGULAR', 'TEMPORARY', 'YOYAKU', name='referencetype'), nullable=False),
    sa.Column('item_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('weight_grams', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('reference_type', 'item_code'),
    schema='public',
    comment='システムで取り扱う商品の基本情報を管理するテーブル'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product', schema='public')
    # ### end Alembic commands ###
